# Sentiment Analyzer Service
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analyzer-service
spec:
  selector:
    app: sentiment-analyzer
  ports:
    - protocol: TCP
# Sentiment Analyzer Service
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analyzer-service
spec:
  selector:
    app: sentiment-analyzer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# Sentiment Analyzer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analyzer
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
        - name: sentiment-analyzer
          image: sentiment-analyzer
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
# Sentiment Analyzer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analyzer
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
        - name: sentiment-analyzer
          image: sentiment-analyzer
          imagePullPolicy: Never
          ports:
            - containerPort: 5000


---
# Sentiment Analyzer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analyzer
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
        - name: sentiment-analyzer
          image: sentiment-analyzer
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
# Sentiment Analyzer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analyzer
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
        - name: sentiment-analyzer
          image: sentiment-analyzer
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
